# Generated by Django 3.0.7 on 2020-07-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FL', 'Flights'), ('ML', 'Meals'), ('IT', 'Internet'), ('PH', 'Phone Bill'), ('SS', 'Social Security')], default='ML', max_length=2)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
