# Generated by Django 3.0.7 on 2020-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myexpenses',
            name='image',
            field=models.FilePathField(path='/my_expenses/img'),
        ),
    ]
