# Generated by Django 3.0.7 on 2020-07-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_expenses', '0002_auto_20200706_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myexpenses',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
