# Generated by Django 3.0.7 on 2020-07-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_expenses', '0004_auto_20200719_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myexpenses',
            name='attachment',
            field=models.FileField(upload_to='my_expenses/receipts/'),
        ),
    ]
