# Generated by Django 3.0.7 on 2020-07-21 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_expenses', '0005_auto_20200719_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(default='Expense Name', max_length=100)),
                ('description', models.CharField(default='Description', max_length=240)),
                ('recepit_date', models.DateField(default=django.utils.timezone.now, max_length=10)),
                ('receipt_num', models.CharField(default='1', max_length=32)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_perc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor_name', models.CharField(default='Vendor', max_length=100)),
                ('vendor_vat', models.CharField(default=' ', max_length=20)),
                ('vendor_address', models.CharField(default='address', max_length=100)),
                ('country', models.CharField(default='España', max_length=30)),
                ('category', models.CharField(default='category', max_length=100)),
                ('attachment', models.FileField(upload_to='receipts/')),
            ],
        ),
        migrations.AlterField(
            model_name='myexpenses',
            name='attachment',
            field=models.FileField(upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='myexpenses',
            name='category',
            field=models.CharField(default='category', max_length=100),
        ),
    ]
