# Generated by Django 3.0.7 on 2021-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_expenses', '0007_delete_myexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recepit_date',
            field=models.DateField(max_length=10),
        ),
    ]
